repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: lint-sol
        name: "lint solidity"
        description: "Checks Solidity code according to the package's linter configuration"
        language: node
        entry: solhint
        files: '\.sol$'
        args:
          - --config=./.solhint.json
          - --ignore-path=./.solhintignore
          - ./contracts/**/*.sol
        additional_dependencies:
          - solhint
          - solhint-plugin-prettier
          - prettier
          - prettier-plugin-solidity
