on: ["push", "pull_request"]

name: main workflow

env:
  # ETHERSCAN_TOKEN:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # WEB3_INFURA_PROJECT_ID:

  # increasing available memory for node reduces issues with ganache crashing
  # https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Compiler Installations
        uses: actions/cache@v2
        with:
          path: |
            ~/.solcx
            ~/.vvm
          key: compiler-cache

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install

      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          cache: "pip"
          python-version: "3.11"
      - run: pip install . -r requirements.txt

      - name: Run Ape Tests
        run: ape test

      - name: Run TS Tests
        run: npm run test

  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Solhint and Prettier
        run: npm install -g solhint solhint-plugin-prettier prettier

      - name: Install Solidity plugin for Prettier
        run: npm install prettier-plugin-solidity

      - name: Solidity Lint
        run: solhint 'contracts/**/*.sol'

      - name: Python Lint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0
        continue-on-error: true
        with:
          args: "pylint **/*.py"
